### ISSUE TITLE
Blur fires before click in IE so scopes disappear without loading search

### ISSUE THREAD

**Issue by quist00** [quist00/onesearch-local#10]
Blur fires before click in IE so scopes disappear without loading search

**Comment by Steve-A-Orr** [comment]
I agree. It looks like that even if you make a selection with the mouse, the scope doesn't change or fire off the search event, like it once did.

**Comment by Steve-A-Orr** [comment]
So, after exposing the IE shims (as described in #8) and **not implementing** any other changes, my tests in _IE 11_ don't show any problems. I'm able to tab successfully; use the mouse to select buttons or scopes successfully; and even just hit Enter successfully.

I guess I don't understand the behavior you're describing. (I can provide my testing instance, if you'd like to confirm.) I think I'll **need a little more detail** in order to replicate your issue.

**Comment by MLKApp** [comment]
I experienced the same issue in IE, FF and Chrome.  When you click a link from the scope, it just disappear with loading search.

**Comment by quist00** [comment]
this should be resolved
